### PR TITLE
Bump docker to version 11.1.2

### PR DESCRIPTION
**Pull request by gurkanindibay**
pg 15 is not integrated into pipeline I will bake and push it manually

### CODE REVIEW

**Review by hanefi — CHANGES_REQUESTED** [review]
- Remove tools submodule
- What about hyperscale images? Should we update them as well?
- What about PG12 ? As we dropped support for that PG version already, why don't we delete the `Dockerfile` for that?

**Comment by gurkanindibay** [comment]
> * Remove tools submodule
> * What about hyperscale images? Should we update them as well?
> * What about PG12 ? As we dropped support for that PG version already, why don't we delete the `Dockerfile` for that?

Actually hyperscale files are being used manually. Updating hyperscale files are not standard process for releases
We need to ask it @marcocitus since he can use it for previous versions as well.
But IMO there is no need to update hyperscale files

**Comment by hanefi** [comment]
I do not see any workflows for PG15. Am I missing something here?

**Comment by gurkanindibay** [comment]
> I do not see any workflows for PG15. Am I missing something here?

​​​​​​​​​​As I write in description, I'm pushing it manually for now I need to change latest into pg 15 and will need to move latest Dockerfile into pg 14, need to change tools code that processing Dockerfiles.
I will all handle them after pg 15 release

**Comment by gurkanindibay** [comment]
> Hadolint output for this run:
> 
> ```json
> {
>   "runs": [
>     {
>       "results": [
>         {
>           "ruleId": "DL3008",
>           "message": {
>             "text": "Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`"
>           },
>           "level": "warning",
>           "locations": [
>             {
>               "physicalLocation": {
>                 "region": {
>                   "sourceLanguage": "dockerfile",
>                   "startColumn": 1,
>                   "endColumn": 1,
>                   "startLine": 17,
>                   "endLine": 17
>                 },
>                 "artifactLocation": { "uri": "./Dockerfile" }
>               }
>             }
>           ]
>         },
>         {
>           "ruleId": "DL3015",
>           "message": {
>             "text": "Avoid additional packages by specifying `--no-install-recommends`"
>           },
>           "level": "note",
>           "locations": [
>             {
>               "physicalLocation": {
>                 "region": {
>                   "sourceLanguage": "dockerfile",
>                   "startColumn": 1,
>                   "endColumn": 1,
>                   "startLine": 17,
>                   "endLine": 17
>                 },
>                 "artifactLocation": { "uri": "./Dockerfile" }
>               }
>             }
>           ]
>         },
>         {
>           "ruleId": "SC2086",
>           "message": {
>             "text": "Double quote to prevent globbing and word splitting."
>           },
>           "level": "note",
>           "locations": [
>             {
>               "physicalLocation": {
>                 "region": {
>                   "sourceLanguage": "sh",
>                   "startColumn": 1,
>                   "endColumn": 1,
>                   "startLine": 17,
>                   "endLine": 17
>                 },
>                 "artifactLocation": { "uri": "./Dockerfile" }
>               }
>             }
>           ]
>         },
>         {
>           "ruleId": "DL4006",
>           "message": {
>             "text": "Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check"
>           },
>           "level": "warning",
>           "locations": [
>             {
>               "physicalLocation": {
>                 "region": {
>                   "sourceLanguage": "dockerfile",
>                   "startColumn": 1,
>                   "endColumn": 1,
>                   "startLine": 17,
>                   "endLine": 17
>                 },
>                 "artifactLocation": { "uri": "./Dockerfile" }
>               }
>             }
>           ]
>         },
>         {
>           "ruleId": "DL3059",
>           "message": {
>             "text": "Multiple consecutive `RUN` instructions. Consider consolidation."
>           },
>           "level": "note",
>           "locations": [
>             {
>               "physicalLocation": {
>                 "region": {
>                   "sourceLanguage": "dockerfile",
>                   "startColumn": 1,
>                   "endColumn": 1,
>                   "startLine": 40,
>                   "endLine": 40
>                 },
>                 "artifactLocation": { "uri": "./Dockerfile" }
>               }
>             }
>           ]
>         }
>       ],
>       "tool": {
>         "driver": {
>           "fullName": "Haskell Dockerfile Linter",
>           "shortDescription": {
>             "text": "Dockerfile linter, validate inline bash, written in Haskell"
>           },
>           "name": "Hadolint",
>           "version": "v2.9.3-0-g346e419-dirty",
>           "downloadUri": "https://github.com/hadolint/hadolint"
>         }
>       },
>       "defaultSourceLanguage": "dockerfile"
>     }
>   ],
>   "version": "2.1.0",
>   "$schema": "http://json.schemastore.org/sarif-2.1.0"
> }
> ```
I will fix it wth this issue
https://github.com/citusdata/docker/issues/321

**Review by hanefi — APPROVED** [review]
All that is left is locally creating and pushing PG15 images.

**Pull request merged**
