### PR TITLE
Bump docker to version 10.0.4

### PR DESCRIPTION
**Pull request by gurkanindibay**

### CODE REVIEW

**Comment by hanefi** [comment]
PG 13.3 and 12.7 are out. We can bump those in all the occurences.

I suggest you do it manually here, and open a small PR on tools repo to update the PG versions in the templates.

**Comment by hanefi** [comment]
Now that we have GitHub action workflows, do you think that it makes sense to disable Travis by removing the configs?

This will help us see if the workflows actually can push the docker images to Docker Hub.

**Comment by hanefi** [comment]
On https://github.com/citusdata/docker/pull/229/checks?check_run_id=3086199616

We have an error:

> ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

Is it safe to assume everything will go smoothly when this dependency can not be installed?

**Comment by hanefi** [comment]
Why don't we have a nightly docker image workflow in GitHub actions? We have them configured on Travis CI jobs.

**Comment by gurkanindibay** [comment]
> Why don't we have a nightly docker image workflow in GitHub actions? We have them configured on Travis CI jobs.

We have but I've just disabled them all for now. I'll go the Travis pipelines because of the urgency
Travis pipeline for 12 got error. Do you mind going with 12.6 for now and opening an issue for updating postgres 12 image to postgres 12.7 to make the things quicker for this release?

**Comment by gurkanindibay** [comment]
> On https://github.com/citusdata/docker/pull/229/checks?check_run_id=3086199616
> 
> We have an error:
> 
> > ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
> 
> Is it safe to assume everything will go smoothly when this dependency can not be installed?

By the way I can not see the error message you pasted? Where did you got this error?

**Comment by hanefi** [comment]
> By the way I can not see the error message you pasted? Where did you got this error?

`Install python requirements` section, line 93

Try this link: https://github.com/citusdata/docker/pull/229/checks?check_run_id=3086199616#step:5:93

**Comment by gurkanindibay** [comment]
There is a difference between travis build and github actions build
travis build failed for postgres 12 and github action did not fail for it
I need to check this.  For now, it is safe to use travis pipelines

**Review by hanefi — APPROVED** [review]
We had a discussion offline and decided to keep doxker hub and travis active until we are sure that the GH action workflows are complete

**Pull request merged**
