### PR TITLE
Persist data with a citus cluster

### PR DESCRIPTION
**Pull request by eduohe**
With the Citus team help we got this solution for the issue https://github.com/citusdata/docker/issues/57

### CODE REVIEW

**Comment by jasonmp85** [comment]
Does this even fix #57? That issue says that shards on the machines which go down are removed from the coordinator's metadata…

**Comment by eduohe** [comment]
@jasonmp85 sorry today we had the same error message mentioned in the issue ``could not find length of shard ...` so this PR didn't fix it. We are using Citus locally on our development team. Any solution planned for this?

**Comment by jasonmp85** [comment]
The `docker-compose` in this repository was always intended as an example for users to play around with and get a quick taste of Citus. The Docker image itself was intended as a usable base for others to build atop. I'll keep looking into the persistence issue, but ultimately users will need to make changes specific to their needs, since this isn't going to e.g. serve local development and deployment equally well.

**Comment by eduohe** [comment]
@jasonmp85 I see, thanks for your answer, but looks that it's a bug reported already https://github.com/citusdata/docker/issues/57#issuecomment-351201430

**Comment by colton-citus** [comment]
I'm pretty sure that this is the culprit: 

https://github.com/citusdata/membership-manager/issues/4

**Comment by eduohe** [comment]
The issue will be fixed with the PR https://github.com/citusdata/membership-manager/pull/5 thanks @colton-citus

**Pull request closed without merging**
