### PR TITLE
Bump docker to version 11.1.4

### PR DESCRIPTION
**Pull request by gurkanindibay**

### CODE REVIEW

**Review by hanefi — CHANGES_REQUESTED** [review]
Please remove the submodule.

**Comment by gurkanindibay** [comment]
> Please remove the submodule.

Removed. I think there is a problem creating this invalid dependency in tools. I opened an issue to remove this dependency

**Review by hanefi — APPROVED** [review]
The changes are ok. However I think we should remove the Dockerfile for PG12 as well.

**Comment by gurkanindibay** [comment]
> The changes are ok. However I think we should remove the Dockerfile for PG12 as well.

I will remove it in another PR

**Pull request merged**
