### PR TITLE
Adds pkgvars to get latest pg version

### PR DESCRIPTION
**Pull request by gurkanindibay**
Previously, postgres 13 and postgres 12 versions were hardcoded in tools repo. I opened a PR to change this beahviour and get versions from pkgvars in docker repo.
pkgvars is required to unit test https://github.com/citusdata/tools/pull/197. This PR is required to be merged master to be able to unit test this PR from master

### CODE REVIEW

**Comment by onurctirtir** [comment]
where exactly do we use those settings ?

**Comment by onurctirtir** [comment]
> where exactly do we use those settings ?

Oh, it is https://github.com/citusdata/tools/pull/197/files, nvm

**Comment by onurctirtir** [comment]
Will try to review this pr today.

**Review by hanefi — APPROVED** [review]
I am ok with the changes here.

However please wait until https://github.com/citusdata/tools/pull/197 gets approved and you also get an approval from Onur before merging this.

**Comment by onurctirtir** [comment]
LGTM too

**Comment by gurkanindibay** [comment]
> LGTM too

@onurctirtir  Could you approve the PR please?

**Pull request merged**
