### PR TITLE
Adds hadolint Dockerfile linter

### PR DESCRIPTION
**Pull request by gurkanindibay**
Hadolint is a dockerfile checker. I added it to be able to validate Dockerfiles
More details: https://hub.docker.com/r/hadolint/hadolint

### CODE REVIEW

**Comment by hanefi** [comment]
Can you update the description with some information on hadolint? Your intention or motivation is not really visible here.

**Comment by hanefi** [comment]
1. I guess the tool only checks `./Dockerfile` You may need to pass some additional parameters to let it know about nightly, alpine, pg13 etc
2. I could not find the interface for checking the results. Can you share how we can inspect results?
3. Does the linter find anything that we can improve? If there are any findings can we also solve them here on this PR?

**Comment by gurkanindibay** [comment]
> 1. I guess the tool only checks `./Dockerfile` You may need to pass some additional parameters to let it know about nightly, alpine, pg13 etc
> 2. I could not find the interface for checking the results. Can you share how we can inspect results?
> 3. Does the linter find anything that we can improve? If there are any findings can we also solve them here on this PR?

1. I wanted to start it with dockerfile. 
2. It does not execute under non-main branches. So we need to wait it until merge. Or I need to show you in another repo 
3. Not yet.

**Comment by hanefi** [comment]
I recently created a new workflow definition on a branch, opened a PR, and I was able to see the results of statical analysis before I merged anything

See https://github.com/citusdata/citus/pull/5868/checks?check_run_id=7112609347

I guess it is not properly set-up, as there is no indication that the sarif file actually is processed somehow.

**Comment by gurkanindibay** [comment]
> I ran the tool locally, and here are the results on `./Dockerfile`:
> 
> ```
> ../docker/Dockerfile:17 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
> ../docker/Dockerfile:17 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
> ../docker/Dockerfile:17 SC2086 info: Double quote to prevent globbing and word splitting.
> ../docker/Dockerfile:17 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
> ../docker/Dockerfile:40 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
> ```
> 
> All the warnings look reasonable to me.

​​​​​​​​​​​​​​​​I managed to add it into the PR but formatting is not readable :(
https://github.com/citusdata/docker/pull/301#issuecomment-1184282230

**Comment by gurkanindibay** [comment]
I need to pause that task. I need to finish my privacy review

**Comment by hanefi** [comment]
Here are the findings on this PR:

https://github.com/citusdata/docker/security/code-scanning?query=pr%3A301

The link is not so easy to find, but I was able to see the results there.

**Comment by gurkanindibay** [comment]
> Here are the findings on this PR:
> 
> https://github.com/citusdata/docker/security/code-scanning?query=pr%3A301
> 
> The link is not so easy to find, but I was able to see the results there.

yikes. It was very hard to find :O

**Comment by gurkanindibay** [comment]
we can start no-fail: false so that we need to fix the messages before merging

**Review by hanefi — APPROVED** [review]
I think this is a good starting point. Here are some ideas for future improvement:

1. Add other Dockerfiles in a matrix
2. Fix the warnings and info messages
3. Improve automated comments

**Comment by gurkanindibay** [comment]
now we can see warnings :)

**Pull request merged**
