### PR TITLE
change the naming of postgres 12 docker file in compliance with the naming strategy of rhe project

### PR DESCRIPTION
**Pull request by gurkanindibay**

### CODE REVIEW

**Comment by hanefi** [comment]
The changes are ok. However I have some other recommendations, and a question:

## Git usage:
- Keep the commit message summary limited to 50 chars. If you need to add more info, wrap your message in 72 chars. Ideally you shuold also have a blank line after the summary as well.
- On your commit messages, start with a capital letter.

## Completeness
Please consider making similar changes for alpine images for the sake of completeness and consistency.

## Question
What is this `rhe project`? Did you mean `the project` maybe?

**Comment by gurkanindibay** [comment]
> The changes are ok. However I have some other recommendations, and a question:
> 
> ## Git usage:
> * Keep the commit message summary limited to 50 chars. If you need to add more info, wrap your message in 72 chars. Ideally you shuold also have a blank line after the summary as well.
> * On your commit messages, start with a capital letter.
> 
> ## Completeness
> Please consider making similar changes for alpine images for the sake of completeness and consistency.
> 
> ## Question
> What is this `rhe project`? Did you mean `the project` maybe?

I will fix the commit message when squashing it 
I think that there is no need for pg 12 for Alpine now. Docker builds are taking too much time and adding an alpine for pg 12 also means all of ther versions like x.y.z x.y which will make our build even longer

**Comment by hanefi** [comment]
I do not think that we need alpine for different versions of PG. I think having only the latest is enough.

Please see https://github.com/citusdata/docker/commit/248c91b46cc9d1f2dee880e242670c6b1258ea64 and cherry pick it to this branch if you it makes sense.

**Review by hanefi — APPROVED** [review]

**Comment by hanefi** [comment]
> I will fix the commit message when squashing it

nit, 5c4ea514065baefa3dc7460f3130faecf5a6b968 commit got merged into master with a long (>52 chars) message. No big deal but could have been better.

**Pull request merged**
